### ISSUE TITLE
[BUG] Attempting to log into the Cydia Store shows white screen

### ISSUE THREAD

**Issue by BobHackett2** [AppTapp/Installer-Issues#167]

**Comment by BobHackett2** [comment]
Describe the bug:
As title states.

To Reproduce:
Steps to reproduce the behaviour:
Try to log into the Cydia store.

Does the issue always occur when trying to reproduce it?
Yes

Expected behavior:
Normal login experience

Screenshots or videos:
None.  Just a white screen, however, it seems to “kind of” work.  It seems as if the page is somewhere behind the whiteness because if you tap in the right areas, the page acts as it should (i.e., tapping on the google button on the Cydia page brings you to the google login page, which is also white, where you will be able to enter your login credentials, again, provided you tap in the right area.)

Device (please complete the following information):

Installer version: 5.0.3 (latest stable version) and 5.1 beta
iOS: iOS 14.3
Jailbreak: unc0ver
Device: iPhone 12 Pro Max

Additional context:
None.

**Comment by t37537** [comment]
Bug

**Comment by vanwijkdave** [comment]
Fixed!

**Comment by vanwijkdave** [comment]
and fixed!

**Comment by BobHackett2** [comment]
I still see a white screen.  Do I need to update to a new version of installer or something?  Thanks!

On Apr 2, 2021, at 5:38 AM, Dave van Wijk ***@***.***> wrote:

﻿
and fixed!

**Comment by vanwijkdave** [comment]
I fixed it in our internal built, once I've done enough updates to it we'll make it public among with other ones!

**Comment by BobHackett2** [comment]
﻿
﻿
﻿
Got it.  Thanks!

On Apr 2, 2021, at 9:54 AM, Dave van Wijk ***@***.***> wrote:

﻿
I fixed it in our internal built, once I've done enough updates to it we'll make it public among with other ones!
