### ISSUE TITLE
Purchase missing from repo store, not downloading.

### ISSUE THREAD

**Issue by Grapplerone** [AppTapp/Installer-Issues#33]
**Describe the issue**
I purchased Gesto and it was shown in Dynastic repo along with Homelist. I had uninstalled it to test a different switcher. I then tried to install it and kept getting and error box saying it could not find it. Looked at my store purchases and it was not showing. It is showing purchased in zebra and Cydia. After reinstalling Zebra & Installer, Zebra was seeing Gesto purchase but installer was not. Was able to install it with Zebra or Cydia but not Installer. 

Once installed with Zebra, Installer saw the purchase from the depiction but the Dynastic store still has it missing. Zebra shows it in the store. 

Logout/login to dynastic yielded same result.

**To Reproduce**
1. Try to download, fails until installed with 3rd party app. After that it works.
2. Look in Dynastic store, app is missing.
3.look at depiction app shows purchased
4.

**Does the issue always occur when trying to reproduce it?** ??

**Expected behavior
see my purchase in Dynastic repo

**Screenshots**

![1A5A7915-06F4-45FD-A4E2-5D836C3826CC](https://user-images.githubusercontent.com/8892548/75584723-5e03c900-5a3e-11ea-8f24-97947ded1643.jpeg)
![59CECE78-0DC5-4B89-A546-E0AA8FB6F96D](https://user-images.githubusercontent.com/8892548/75584724-5e9c5f80-5a3e-11ea-8cab-8ce8d94c1d2b.png)

**Device (please complete the following information):**
 - Device: [Iphone 11]
 - OS: [iOS 13.3]
 - Version [Installer 5.0.2.2]
 - Jailbreak [Unc0ver 4.2.1]

**Additional context**.

**DO NOT FORGET TO LABEL THIS REPORT**

**Comment by AppTapp** [comment]
This issue should be solved on recent versions. Could you confirm this?

**Comment by Grapplerone** [comment]
It still does NOT show up as a purchase via Installer.

It does via Zebra’s Dynastic store
